### ISSUE TITLE
"Use image signal" is always True

### ISSUE THREAD

**Issue by ghost** [vslaykovsky/elonbot#2] opened 2021-05-21 03:17 UTC
I'm using these arguments and I'm not using the --use-image-signal argument
```
python elonbot.py --user=elonmusk --margin-type=cross_margin --crypto-rules="{""doge"": ""DOGE""}" --auto-buy-delay 1 --auto-sell-delay=60 --order-size=max --dry-run --asset USDT --process-tweet "{""data"": {""text"": ""Dodge coin is not what we need""}}"
```

But I still get Use image signal: True
```2021-05-21 05:07:51.516164 Starting elon.py
2021-05-21 05:07:51.516164   User: elonmusk
2021-05-21 05:07:51.517163   Crypto rules: {'doge': 'DOGE'}
2021-05-21 05:07:51.517163   self.asset: USDT
2021-05-21 05:07:51.517163   Auto buy time: 1.0
2021-05-21 05:07:51.518160   Auto sell time: 60.0
2021-05-21 05:07:51.519158   Use image signal: True
2021-05-21 05:07:51.519158   Margin type: MarginType.CROSS_MARGIN
2021-05-21 05:07:51.519158   Order size: max
2021-05-21 05:07:51.520155 Tweet received
 {
    "data": {
        "text": "Dodge coin is not what we need"
    }
}
```

When I keep `"includes": {"media": [{"url": "..."}]}` in the process-tweet I get an error because my GOOGLE_APPLICATION_CREDENTIALS is not set correctly, but I don't want to use it.

**Comment by vslaykovsky** [comment] 2021-05-21 08:09
Than you for the report. The issue is fixed with https://github.com/vslaykovsky/elonbot/commit/04c8683d9f6611030bcbe3d9aebe20e2c5c2e6f3

**Closed as completed by vslaykovsky** 2021-05-21 08:09 UTC
